name: Build and test

on:
  release:
    types: [created]

  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Ensure dependencies are installed
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-asyncio

    - name: Build package and install
      run: |
        python -m pip wheel . --wheel-dir dist
        python -m pip install dist/snakecore*

    - name: Run tests
      # no color on CI
      run: pytest -v --color=no
      working-directory: tests

    - name: Upload files to Github Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: snakecore-builds
        path: dist/snakecore*

# TODO
#   - name: Upload files to Github Releases
#     if: github.event_name == 'release'
#     uses: svenstaro/upload-release-action@v2
#     with:
#       repo_token: ${{ secrets.GITHUB_TOKEN }}
#       file: dist/snakecore*
#       tag: ${{ github.ref }}
#
#   - name: Upload files to PyPI
#     if: github.event_name == 'release'
#     uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#     with:
#       user: __token__ # TODO
#       password: ${{ secrets.PYPI_API_TOKEN }}
