name: Build and test

on:
  release:
    types: [created]

  push:
    branches: main

  pull_request:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Set up Python v3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Ensure latest pip is used
      run: python -m pip install --upgrade pip
    
    # temporary block, install discord.py from source
    # after 2.0 release, it will be installed normally from requirements.txt
    - name: Install discord.py dev version
      run: |
        git clone https://github.com/Rapptz/discord.py
        cd discord.py
        python -m pip install . -U

    - name: Build package
      run: python -m pip wheel . --wheel-dir dist

    - name: Upload files to Github Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: snakecore-builds
        path: dist/snakecore*

# TODO
#   - name: Upload files to Github Releases
#     if: github.event_name == 'release'
#     uses: svenstaro/upload-release-action@v2
#     with:
#       repo_token: ${{ secrets.GITHUB_TOKEN }}
#       file: dist/snakecore*
#       tag: ${{ github.ref }}
#
#   - name: Upload files to PyPI
#     if: github.event_name == 'release'
#     uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#     with:
#       user: __token__ # TODO
#       password: ${{ secrets.PYPI_API_TOKEN }}
