name: Run pylint and black

on:
  release:
    types: [created]

  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint black wheel

    - name: Build package and install
      run: |
        python -m pip wheel . --wheel-dir dist
        python -m pip install dist/snakecore*
    
    - name: Linting code with black
      run: black . --check

    - name: Analysing code with pylint
      run: pylint snakecore --fail-under=8
